### PR TITLE
About view

### PR DESCRIPTION
**Pull request by sonph**
This includes a quick description of the project and relevant information (open source, license, repos, etc.) and team members.

screenshot 2015-10-04 15 06 32

I'll need each of you @LeBat @Tsintsir @shawkinsl to send me
- a profile pic
- a short description (1-2 sentences)

and I'll add it to your card (or you can open a PR from this branch).

### CODE REVIEW

**Comment by sonph** [comment]
Or we can also come up with some funny titles like [this](http://justsomething.co/hilarious-job-titles/)

**Comment by Spencatro** [comment]
What the hell dude I am **not** just a very simply card. Rude.

**Comment by Spencatro** [comment]
but for real, I'm fine with the goofy titles thing if we can stay sfw (and bonus points for being related to project) and my tagline/bio can be:

Spencer Hawkins
(goofy title) door-to-door git evangelist

Pacific Northwesterner transplanted in Texas. CS student at UTD. Validation engineer at Tesla Motors.

(I can make it first person if that's what others end up going with)

**Comment by sonph** [comment]
For me I'm thinking something like

Son Pham
Chief Javascript Wrangler
Asian dude with glasses. Temporary Texas resident. Prospective Noogler.

**Comment by ghost** [comment]
tbh i am a very simple card

**Comment by Spencatro** [comment]
image

**Comment by coffeefee-coder** [comment]
Konrad Ryce
Actually goes by Dustin for unknown reasons.
Learned Python and Flask from some old guy in a swamp.
Eats more candy than he should.

**Comment by coffeefee-coder** [comment]
image

**Comment by ghost** [comment]
https://cloud.githubusercontent.com/assets/13776234/10701401/fbd4445c-7988-11e5-94bb-a22e009a7995.jpg

Tristan Duckworth
Average CS Dude
Advocate for use of assembly in frontend, backend, database, data, frameworks, protocols, coding standards, everyday language, carrier pigeon tail numbers, and cooking recipes

**Comment by sonph** [comment]
1445630876569screensave

**Comment by ghost** [comment]
Maybe make my title "Front End Avoidance Expert"? Since I haven't messed with that side of the work at all for the most part. ;P

**Comment by coffeefee-coder** [comment]
My title can be "Python Handler"
huehue

**Pull request merged**
