### PR TITLE
Refactor front end to use angular instead

### PR DESCRIPTION
**Pull request by sonph**
I'm using 2 spaces tabs and no semicolons, and all controllers are temporarily in the same file for now.
I only used angular for side projects so @Tsintsir @LeBat let me know if you guys have any suggestions.

### CODE REVIEW

**Comment by Spencatro** [comment]
:+1: looks very good!

Can we put a readme or something saying that the images came from unsplash? (found them by googling the filenames). Otherwise, I am good with this merging.

**Comment by sonph** [comment]
Yah I purposefully renamed the imgs to their respective photographer. Not sure where to put credits for the imgs though.

**Comment by Spencatro** [comment]
They're labeled as CC0 (https://unsplash.com/license) so I'm not worried about external credit. More just for internal notice, so a readme seems appropriate

**Comment by sonph** [comment]
Cool I'll just add the credits to the repo's README then.

**Comment by Spencatro** [comment]
Ok looks great, let's get this merged ( @LeBat  @Tsintsir )

**Comment by coffeefee-coder** [comment]
Looks good to me

**Pull request merged**
